version: '3'

services:
    mysql:
        image: mysql:5.6
        container_name: docker-mysql
        environment:
            MYSQL_DATABASE: 'solid_studies'
            MYSQL_USER: 'app'
            MYSQL_PASSWORD: 'my_password'
            MYSQL_ROOT_PASSWORD: 'my_password'
        ports:
            - "33061:3306"
        restart: always

    web:
        image: php:7.4-apache
        container_name: docker-php
        ports:
            - "8000:80"
            - "8001:8001"
        expose:
          - "8001"
        volumes:
            - ./:/var/www/html
        links:
            - mysql
